<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeTypeInterface;

/**
 * Takes a 'CamelCase'' word and adds spaces to make it 'Camel Case'.
 *
 * @return string
 *   A formated string
 */
function opencalais_api_make_readable($camel_case) {
  return preg_replace('/(.*?[a-z]{1})([A-Z]{1}.*?)/', '${1} ${2}', $camel_case);
}

/**
 * A Utility function used to turn any (mainly CamelCase) string into a valid machine name
 */
function opencalais_make_machine_name($name) {
  $name = str_replace(' ', '_', $name);
  $name = preg_replace('/([a-z])([A-Z])/', '$1_$2', $name);
  $name = strtolower($name);
  return $name;
}

/**
 * Implements hook_namespaces().
 *
 * Declare the Calais namespaces for RDF/RDFa support.
 */
function opencalais_api_rdf_namespaces() {
  return array(
    'c' => 'http://s.opencalais.com/1/pred/',
    'sys' => 'http://s.opencalais.com/1/type/sys/',
    'lid' => 'http://s.opencalais.com/1/type/lid/',
    'cat' => 'http://s.opencalais.com/1/type/cat/',
    'resolved' => 'http://s.opencalais.com/1/type/er/',
    'cgeo' => 'http://s.opencalais.com/1/type/er/Geo/',
    'eventfact' => 'http://s.opencalais.com/1/type/em/r/',
    'entity' => 'http://s.opencalais.com/1/type/em/e/',
    'cld' => "http://s.opencalais.com/1/linkeddata/pred/",
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function opencalais_api_form_node_type_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $options = [];
  $field_definitions = \Drupal::service('entity_field.manager')
    ->getFieldDefinitions('node', $form_state->getFormObject()
      ->getEntity()
      ->get('type'));

  foreach ($field_definitions as $field_name => $field_definition) {
    if ($field_definition->getType() == 'entity_reference') {
      if ($field_definition->getFieldStorageDefinition()->getSetting('target_type') == 'taxonomy_term') {
        $options[$field_definition->getName()] = $field_definition->getLabel();
      }
    }
  }

  if ($options) {
    $form['opencalais_field'] = [
      '#title' => t('OpenCalais Field'),
      '#description' => t('Field where to add taxonomy terms.'),
      '#type' => 'select',
      '#options' => $options,
      '#default_value' => $form_state->getFormObject()->getEntity()->getThirdPartySetting('opencalais_api', 'field'),
      '#empty_option' => t('None'),
    ];
  }
  $form['#entity_builders'][] = 'opencalais_api_form_node_type_form_submit';
}

/**
 * Entity builder for the node type form with opencalais fields.
 *
 * @see opencalais_api_form_node_type_form_alter()
 */
function opencalais_api_form_node_type_form_submit($entity_type, NodeTypeInterface $type, &$form, FormStateInterface $form_state) {
  $type->setThirdPartySetting('opencalais_api', 'field', $form_state->getValue('opencalais_field'));
}
