opencalais_api.settings:
  type: config_object
  label: 'Settings'
  mapping:
    api_key:
      type: string
      label: 'API Key of the service'
    api_server:
      type: string
      label: 'API Server of the service'
