opencalais_ui.settings:
  type: config_object
  label: 'Settings'
  mapping:
    api_key:
      type: string
      label: 'API Key of the service'
    api_server:
      type: string
      label: 'API Server of the service'

node.type.*.third_party.opencalais_ui:
  type: mapping
  label: 'Open Calais per-node type third party settings.'
  mapping:
    field:
      type: string
      label: 'Field where to store Open Calais tags on node type.'
